---
#- name: Include "{{ansible_os_family}}" SGE recipe
#  include: "{{ansible_os_family}}.yaml"

  
- name: Copy 'im.conf' file to /etc/tmpfiles.d/ prevents tmp del
  copy: dest=/etc/tmpfiles.d/im.conf src=im.conf mode=0644 force=no
  
# LRMS configuration
#- name: Configuring the elastic cluster to use "{{queue_system}}" LRMS
#  include: "{{queue_system}}.yaml"
#  when: {{queue_system}} == "sge"
  
- name: Change PasswordAuthentication yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: PasswordAuthentication yes

- name: Add StrictHostKeyChecking no
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: '^PasswordAuthentication'
    line: StrictHostKeyChecking no

- name: Add UserKnownHostsFile /dev/null
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: '^UserKnownHostsFile'
    line: UserKnownHostsFile /dev/null
  
- name: restart sshd
  service: name=sshd state=restarted


